# Generated by Django 6.0.4 on 2026-04-21 07:02

import django.db.models.deletion
import django.utils.timezone
import radios.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_receptionniste_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('dentiste_id', models.UUIDField(db_index=True, verbose_name='UUID du dentiste')),
                ('image', models.ImageField(upload_to=radios.models.radio_upload_path, verbose_name='Image radiographique')),
                ('type_radio', models.CharField(choices=[('PANORAMIQUE', 'Panoramique'), ('PERIAPICALE', 'Périapicale'), ('BITEWING', 'Bitewing (interproximale)'), ('OCCLUSAL', 'Occlusal'), ('CEPHALOMETRIQUE', 'Céphalométrique'), ('CONE_BEAM', 'Cone Beam (3D)'), ('AUTRE', 'Autre')], db_index=True, default='PANORAMIQUE', max_length=20, verbose_name='Type de radiographie')),
                ('description', models.TextField(blank=True, verbose_name='Description / observations du dentiste')),
                ('date_prise', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de prise de la radio')),
                ('statut_analyse', models.CharField(choices=[('EN_ATTENTE', "En attente d'analyse"), ('EN_COURS', 'Analyse en cours'), ('ANALYSE', 'Analysée'), ('ERREUR', "Erreur d'analyse")], db_index=True, default='EN_ATTENTE', max_length=15, verbose_name="Statut de l'analyse IA")),
                ('ia_resultat', models.TextField(blank=True, help_text='Résumé textuel retourné par le modèle IA.', verbose_name="Résultat de l'analyse IA")),
                ('ia_anomalies', models.JSONField(blank=True, help_text='Liste structurée des anomalies retournée par ia_service.', null=True, verbose_name='Anomalies détectées (JSON)')),
                ('ia_confidence', models.FloatField(blank=True, help_text='Score de confiance global du modèle IA (0.0 → 1.0).', null=True, verbose_name='Score de confiance global')),
                ('ia_anomalies_detectees', models.BooleanField(db_index=True, default=False, help_text="True si l'IA a détecté au moins une anomalie.", verbose_name='Anomalies détectées')),
                ('ia_analyse_at', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'analyse IA")),
                ('ia_erreur', models.TextField(blank=True, verbose_name="Message d'erreur IA")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Radiographie',
                'verbose_name_plural': 'Radiographies',
                'ordering': ['-date_prise', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='radios_radi_patient_814401_idx'), models.Index(fields=['dentiste_id', 'is_active'], name='radios_radi_dentist_09aadd_idx'), models.Index(fields=['statut_analyse', 'is_active'], name='radios_radi_statut__959999_idx'), models.Index(fields=['date_prise', 'is_active'], name='radios_radi_date_pr_9aa2b1_idx')],
            },
        ),
    ]
