# Generated by Django 6.0.4 on 2026-04-25 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='date_prise',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date de prise de la radio'),
        ),
    ]
