# Generated by Django 6.0.4 on 2026-04-13 21:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format invalide. Ex : 0551234567 ou +213551234567', regex='^\\+?[0-9]{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('INCONNU', 'Non renseigné')], default='INCONNU', max_length=10, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('antecedents', models.TextField(blank=True, verbose_name='Antécédents médicaux')),
                ('medicaments_actuels', models.TextField(blank=True, verbose_name='Médicaments actuels')),
                ('note_generale', models.TextField(blank=True, verbose_name='Note générale')),
                ('alerte_anticoagulants', models.BooleanField(default=False, help_text='Risque hémorragique — adapter les soins.', verbose_name='Sous anticoagulants')),
                ('alerte_diabete', models.BooleanField(default=False, help_text='Vérifier glycémie, cicatrisation lente.', verbose_name='Diabétique')),
                ('alerte_grossesse', models.BooleanField(default=False, help_text='Éviter rayons X, certains anesthésiques.', verbose_name='Enceinte')),
                ('alerte_allergie_latex', models.BooleanField(default=False, help_text='Utiliser matériel sans latex.', verbose_name='Allergie au latex')),
                ('alerte_cardiopathie', models.BooleanField(default=False, help_text='Antibioprophylaxie possible.', verbose_name='Cardiopathie')),
                ('alerte_immunodeprime', models.BooleanField(default=False, help_text='Précautions antiseptiques renforcées.', verbose_name='Immunodéprimé')),
                ('dentiste_id', models.IntegerField(db_index=True, verbose_name='ID du dentiste référent')),
                ('statut', models.CharField(choices=[('ACCEPTE', 'Accepté'), ('PENDING', 'En attente de validation'), ('REFUSE', 'Refusé')], db_index=True, default='ACCEPTE', max_length=10, verbose_name='Statut de validation')),
                ('refuse_raison', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dentiste_id', 'is_active'], name='patients_pa_dentist_ee8b8a_idx'), models.Index(fields=['statut', 'is_active'], name='patients_pa_statut_df9109_idx'), models.Index(fields=['nom', 'prenom'], name='patients_pa_nom_d8dfda_idx'), models.Index(fields=['date_naissance'], name='patients_pa_date_na_efca25_idx')],
            },
        ),
    ]
