# Generated by Django 6.0.4 on 2026-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='archived_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dentiste_id',
            field=models.UUIDField(db_index=True, verbose_name='UUID du dentiste référent'),
        ),
    ]
