# Generated by Django 6.0.4 on 2026-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_archived_by_alter_patient_dentiste_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='receptionniste_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID de la réceptionniste qui a créé le patient'),
        ),
    ]
