# Generated by Django 6.0.4 on 2026-04-21 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinataire_id', models.UUIDField(db_index=True, verbose_name='UUID du destinataire')),
                ('acteur_id', models.UUIDField(blank=True, null=True, verbose_name="UUID de l'acteur")),
                ('acteur_nom', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'acteur")),
                ('type', models.CharField(choices=[('PATIENT_EN_ATTENTE', 'Nouveau patient en attente'), ('PATIENT_VALIDE', 'Patient accepté'), ('PATIENT_REFUSE', 'Patient refusé'), ('RDV_EN_ATTENTE', 'Nouveau rendez-vous en attente'), ('RDV_VALIDE', 'Rendez-vous accepté'), ('RDV_REFUSE', 'Rendez-vous refusé'), ('RDV_ANNULE', 'Rendez-vous annulé'), ('RDV_RAPPEL', 'Rappel de rendez-vous'), ('SYSTEME', 'Notification système')], db_index=True, max_length=30, verbose_name='Type de notification')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('ALERTE', 'Alerte'), ('CRITIQUE', 'Critique')], default='INFO', max_length=10, verbose_name='Niveau')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID du patient concerné')),
                ('patient_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du patient (dénormalisé)')),
                ('rdv_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID du rendez-vous concerné')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées (payload événement)')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire_id', 'is_read'], name='notificatio_destina_f86ce4_idx'), models.Index(fields=['destinataire_id', 'created_at'], name='notificatio_destina_d18116_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
    ]
