# Generated by Django 6.0.4 on 2026-04-21 07:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_receptionniste_id'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('dentiste_id', models.UUIDField(db_index=True, verbose_name='UUID du dentiste prescripteur')),
                ('numero', models.CharField(help_text='Généré automatiquement à la création.', max_length=50, unique=True, verbose_name="Numéro d'ordonnance")),
                ('date_prescription', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de prescription')),
                ('date_expiration', models.DateField(blank=True, help_text='Laisser vide si pas de date limite.', null=True, verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], db_index=True, default='ACTIVE', max_length=10, verbose_name='Statut')),
                ('diagnostic', models.TextField(blank=True, help_text='Contexte clinique de la prescription.', verbose_name='Diagnostic / motif')),
                ('instructions_generales', models.TextField(blank=True, help_text="Ex : À prendre avant les repas, éviter l'alcool…", verbose_name='Instructions générales')),
                ('note_pharmacien', models.TextField(blank=True, verbose_name='Note pour le pharmacien')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.patient', verbose_name='Patient')),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='rendezvous.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_prescription', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=200, verbose_name='Médicament (DCI ou nom commercial)')),
                ('dosage', models.CharField(blank=True, help_text='Ex : 500mg, 1g', max_length=100, verbose_name='Dosage')),
                ('forme', models.CharField(choices=[('COMPRIMES', 'Comprimés'), ('GELULES', 'Gélules'), ('SIROP', 'Sirop'), ('INJECTABLE', 'Injectable'), ('CREME', 'Crème / Pommade'), ('COLLYRE', 'Collyre'), ('SPRAY', 'Spray'), ('SACHET', 'Sachet'), ('PATCH', 'Patch'), ('AUTRE', 'Autre')], default='COMPRIMES', max_length=20, verbose_name='Forme galénique')),
                ('voie', models.CharField(choices=[('ORALE', 'Orale'), ('SUBLINGUALE', 'Sublinguale'), ('INJECTABLE', 'Injectable'), ('TOPIQUE', 'Topique'), ('NASALE', 'Nasale'), ('OCULAIRE', 'Oculaire'), ('AUTRE', 'Autre')], default='ORALE', max_length=20, verbose_name="Voie d'administration")),
                ('posologie', models.CharField(help_text='Ex : 1 comprimé matin et soir', max_length=200, verbose_name='Posologie')),
                ('duree_traitement', models.CharField(blank=True, help_text='Ex : 7 jours, 1 mois', max_length=100, verbose_name='Durée du traitement')),
                ('quantite', models.PositiveSmallIntegerField(default=1, verbose_name='Quantité à délivrer')),
                ('instructions', models.TextField(blank=True, help_text='Ex : À prendre après le repas, ne pas écraser.', verbose_name='Instructions spécifiques')),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ordonnances.ordonnance', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
                'ordering': ['ordonnance', 'ordre'],
            },
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['dentiste_id', 'is_active'], name='ordonnances_dentist_a4c998_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['patient', 'is_active'], name='ordonnances_patient_ce1d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['statut', 'is_active'], name='ordonnances_statut_f8e165_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['date_prescription'], name='ordonnances_date_pr_53dabf_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['date_expiration'], name='ordonnances_date_ex_142c64_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneordonnance',
            index=models.Index(fields=['ordonnance', 'ordre'], name='ordonnances_ordonna_d916fa_idx'),
        ),
    ]
