# Generated by Django 6.0.4 on 2026-04-21 07:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_receptionniste_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('dentiste_id', models.UUIDField(db_index=True, verbose_name='UUID du dentiste référent')),
                ('receptionniste_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID de la réceptionniste créatrice')),
                ('date_heure', models.DateTimeField(db_index=True, verbose_name='Date et heure du rendez-vous')),
                ('duree_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Durée (minutes)')),
                ('type_soin', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('DETARTRAGE', 'Détartrage'), ('EXTRACTION', 'Extraction'), ('OBTURATION', 'Obturation / Plombage'), ('COURONNE', 'Couronne'), ('IMPLANT', 'Implant'), ('ORTHODONTIE', 'Orthodontie'), ('RADIOGRAPHIE', 'Radiographie'), ('CHIRURGIE', 'Chirurgie buccale'), ('BLANCHIMENT', 'Blanchiment'), ('CONTROLE', 'Contrôle / Suivi'), ('URGENCE', 'Urgence'), ('AUTRE', 'Autre')], db_index=True, default='CONSULTATION', max_length=30, verbose_name='Type de soin')),
                ('priorite', models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente'), ('HAUTE', 'Haute priorité')], db_index=True, default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente de validation'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], db_index=True, default='ACCEPTE', max_length=10, verbose_name='Statut')),
                ('refuse_raison', models.TextField(blank=True, verbose_name='Raison du refus / annulation')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la consultation')),
                ('note_interne', models.TextField(blank=True, verbose_name='Note interne (dentiste)')),
                ('instructions_patient', models.TextField(blank=True, verbose_name='Instructions pour le patient')),
                ('rappel_envoye', models.BooleanField(default=False, help_text='Mis à True par Celery après envoi du rappel email/SMS.', verbose_name='Rappel envoyé')),
                ('rappel_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du rappel")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_set', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['dentiste_id', 'statut', 'is_active'], name='rendezvous__dentist_ac19be_idx'), models.Index(fields=['dentiste_id', 'date_heure'], name='rendezvous__dentist_4f4f2b_idx'), models.Index(fields=['patient', 'is_active'], name='rendezvous__patient_fbf0ca_idx'), models.Index(fields=['statut', 'is_active'], name='rendezvous__statut_06f6e7_idx'), models.Index(fields=['date_heure', 'statut'], name='rendezvous__date_he_ca6275_idx')],
            },
        ),
    ]
