# Generated by Django 6.0.4 on 2026-04-21 07:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_receptionniste_id'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('dentiste_id', models.UUIDField(db_index=True, verbose_name='UUID du dentiste')),
                ('type_acte', models.CharField(choices=[('CONSULTATION', 'Consultation / Examen'), ('CONTROLE', 'Contrôle / Suivi'), ('DETARTRAGE', 'Détartrage / Surfaçage'), ('BLANCHIMENT', 'Blanchiment dentaire'), ('OBTURATION', 'Obturation / Plombage'), ('INLAY_ONLAY', 'Inlay / Onlay'), ('FACETTE', 'Facette céramique'), ('TRAITEMENT_CANAL', 'Traitement de canal (endodontie)'), ('REPRISE_CANAL', 'Reprise de traitement canalaire'), ('PULPOTOMIE', 'Pulpotomie'), ('APEXIFICATION', 'Apexification'), ('COURONNE', 'Couronne prothétique'), ('BRIDGE', 'Bridge'), ('PROTHESE_PARTIELLE', 'Prothèse partielle amovible'), ('PROTHESE_TOTALE', 'Prothèse totale amovible'), ('PROTHESE_SUR_IMPLANT', 'Prothèse sur implant'), ('EXTRACTION_SIMPLE', 'Extraction simple'), ('EXTRACTION_COMPLEXE', 'Extraction complexe / chirurgicale'), ('DENT_DE_SAGESSE', 'Extraction dent de sagesse'), ('IMPLANT', "Pose d'implant dentaire"), ('GREFFE_OSSEUSE', 'Greffe osseuse'), ('GREFFE_GINGIVALE', 'Greffe gingivale'), ('FRENECTOMIE', 'Frenectomie'), ('PARO_CHIRURGICAL', 'Traitement parodontal chirurgical'), ('PARO_NON_CHIRURGICAL', 'Traitement parodontal non chirurgical'), ('ORTHODONTIE_FIXE', 'Orthodontie fixe (bagues)'), ('ORTHODONTIE_AMOVIBLE', 'Orthodontie amovible (gouttières)'), ('CONTENTION', 'Contention orthodontique'), ('SCELLEMENT', 'Scellement de sillons'), ('FLUORATION', 'Application de fluor'), ('PULPOTOMIE_LACTEAL', 'Pulpotomie dent lactéale'), ('RADIO_PERIAPICALE', 'Radiographie périapicale'), ('RADIO_PANORAMIQUE', 'Radiographie panoramique'), ('RADIO_CEPHALO', 'Radiographie céphalométrique'), ('URGENCE_DOULEUR', 'Urgence douleur'), ('URGENCE_TRAUMA', 'Urgence traumatisme'), ('URGENCE_ABCES', 'Urgence abcès'), ('AUTRE', 'Autre acte')], db_index=True, default='CONSULTATION', max_length=30, verbose_name="Type d'acte")),
                ('description', models.TextField(blank=True, help_text="Détails cliniques de l'acte, technique utilisée, observations.", verbose_name='Description détaillée')),
                ('dent', models.CharField(choices=[('11', '11 — Incisive centrale sup. droite'), ('12', '12 — Incisive latérale sup. droite'), ('13', '13 — Canine sup. droite'), ('14', '14 — 1ère prémolaire sup. droite'), ('15', '15 — 2ème prémolaire sup. droite'), ('16', '16 — 1ère molaire sup. droite'), ('17', '17 — 2ème molaire sup. droite'), ('18', '18 — 3ème molaire sup. droite (sagesse)'), ('21', '21 — Incisive centrale sup. gauche'), ('22', '22 — Incisive latérale sup. gauche'), ('23', '23 — Canine sup. gauche'), ('24', '24 — 1ère prémolaire sup. gauche'), ('25', '25 — 2ème prémolaire sup. gauche'), ('26', '26 — 1ère molaire sup. gauche'), ('27', '27 — 2ème molaire sup. gauche'), ('28', '28 — 3ème molaire sup. gauche (sagesse)'), ('31', '31 — Incisive centrale inf. gauche'), ('32', '32 — Incisive latérale inf. gauche'), ('33', '33 — Canine inf. gauche'), ('34', '34 — 1ère prémolaire inf. gauche'), ('35', '35 — 2ème prémolaire inf. gauche'), ('36', '36 — 1ère molaire inf. gauche'), ('37', '37 — 2ème molaire inf. gauche'), ('38', '38 — 3ème molaire inf. gauche (sagesse)'), ('41', '41 — Incisive centrale inf. droite'), ('42', '42 — Incisive latérale inf. droite'), ('43', '43 — Canine inf. droite'), ('44', '44 — 1ère prémolaire inf. droite'), ('45', '45 — 2ème prémolaire inf. droite'), ('46', '46 — 1ère molaire inf. droite'), ('47', '47 — 2ème molaire inf. droite'), ('48', '48 — 3ème molaire inf. droite (sagesse)'), ('51', '51 — Incisive centrale sup. droite (lact.)'), ('52', '52 — Incisive latérale sup. droite (lact.)'), ('53', '53 — Canine sup. droite (lact.)'), ('54', '54 — 1ère molaire sup. droite (lact.)'), ('55', '55 — 2ème molaire sup. droite (lact.)'), ('61', '61 — Incisive centrale sup. gauche (lact.)'), ('62', '62 — Incisive latérale sup. gauche (lact.)'), ('63', '63 — Canine sup. gauche (lact.)'), ('64', '64 — 1ère molaire sup. gauche (lact.)'), ('65', '65 — 2ème molaire sup. gauche (lact.)'), ('71', '71 — Incisive centrale inf. gauche (lact.)'), ('72', '72 — Incisive latérale inf. gauche (lact.)'), ('73', '73 — Canine inf. gauche (lact.)'), ('74', '74 — 1ère molaire inf. gauche (lact.)'), ('75', '75 — 2ème molaire inf. gauche (lact.)'), ('81', '81 — Incisive centrale inf. droite (lact.)'), ('82', '82 — Incisive latérale inf. droite (lact.)'), ('83', '83 — Canine inf. droite (lact.)'), ('84', '84 — 1ère molaire inf. droite (lact.)'), ('85', '85 — 2ème molaire inf. droite (lact.)'), ('PLUSIEURS', 'Plusieurs dents'), ('ARCADE_SUP', 'Arcade supérieure complète'), ('ARCADE_INF', 'Arcade inférieure complète'), ('TOUTES', 'Toutes les dents'), ('NON_PRECISE', 'Non précisé')], db_index=True, default='NON_PRECISE', max_length=15, verbose_name='Dent traitée (FDI)')),
                ('face_dentaire', models.CharField(blank=True, help_text='Ex : mésiale, distale, occlusale, vestibulaire, linguale', max_length=50, verbose_name='Face(s) dentaire(s)')),
                ('materiau', models.CharField(choices=[('COMPOSITE', 'Composite (résine)'), ('AMALGAME', 'Amalgame'), ('CERAMIQUE', 'Céramique'), ('ZIRCONE', 'Zircone'), ('OR', 'Or / Métal précieux'), ('METAL', 'Métal (non précieux)'), ('CIMENT_VERRE', 'Ciment verre ionomère (CVI)'), ('RESINE_IONOMERE', 'Résine ionomère modifiée'), ('TITANE', 'Titane'), ('ZIRCONE_IMPLANT', 'Zircone (implant)'), ('ACRYLIQUE', 'Acrylique (prothèse)'), ('CHROME_COBALT', 'Chrome-cobalt (squelettée)'), ('ACIER', 'Acier (brackets)'), ('CERAMIQUE_ORTHO', 'Céramique (brackets)'), ('GOUTTIERE_SILICONE', 'Gouttière silicone'), ('AUTRE', 'Autre matériau'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=25, verbose_name='Matériau utilisé')),
                ('materiau_detail', models.CharField(blank=True, help_text='Marque, teinte, référence produit, etc.', max_length=200, verbose_name='Détail matériau')),
                ('date_debut', models.DateField(db_index=True, verbose_name='Date de début du traitement')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (si terminé)')),
                ('duree_estimee_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Durée estimée (minutes)')),
                ('nombre_seances_prevues', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Nombre de séances prévues')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours (multi-séances)'), ('TERMINE', 'Terminé'), ('ABANDONNE', 'Abandonné / Interrompu'), ('EN_ATTENTE', 'En attente (accord mutuelle)')], db_index=True, default='PLANIFIE', max_length=15, verbose_name='Statut du traitement')),
                ('raison_abandon', models.TextField(blank=True, help_text='Rempli si statut = ABANDONNE.', verbose_name="Raison d'abandon")),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût total (DZD)')),
                ('cout_patient', models.DecimalField(decimal_places=2, default=0, help_text='Montant restant à la charge du patient après mutuelle.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Part patient (DZD)')),
                ('est_couvert_mutuelle', models.BooleanField(default=False, verbose_name='Couvert par mutuelle')),
                ('reference_mutuelle', models.CharField(blank=True, max_length=100, verbose_name='Référence / N° accord mutuelle')),
                ('anesthesie_utilisee', models.BooleanField(default=False, verbose_name='Anesthésie utilisée')),
                ('type_anesthesie', models.CharField(blank=True, help_text='Ex : Lidocaïne 2%, bloc nerveux, anesthésie locale', max_length=100, verbose_name="Type d'anesthésie")),
                ('notes_pre_op', models.TextField(blank=True, help_text="Observations avant l'acte, consentement, état initial.", verbose_name='Notes pré-opératoires')),
                ('notes_per_op', models.TextField(blank=True, help_text="Observations pendant l'acte, incidents, technique.", verbose_name='Notes per-opératoires')),
                ('notes_post_op', models.TextField(blank=True, help_text='Consignes données, cicatrisation prévue, suites.', verbose_name='Notes post-opératoires')),
                ('instructions_patient', models.TextField(blank=True, help_text='Ce que le patient doit faire/éviter après le traitement.', verbose_name='Instructions pour le patient')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient', verbose_name='Patient')),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='rendezvous.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeanceSoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_seance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° de séance')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('duree_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Durée (minutes)')),
                ('acte_realise', models.TextField(verbose_name='Acte réalisé lors de cette séance')),
                ('observations', models.TextField(blank=True, verbose_name='Observations cliniques')),
                ('prochain_rdv_notes', models.TextField(blank=True, verbose_name='Notes pour le prochain rendez-vous')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_soin', to='rendezvous.rendezvous', verbose_name='Rendez-vous associé')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='treatments.traitement', verbose_name='Traitement')),
            ],
            options={
                'verbose_name': 'Séance de soin',
                'verbose_name_plural': 'Séances de soin',
                'ordering': ['traitement', 'numero_seance'],
            },
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['dentiste_id', 'is_active'], name='treatments__dentist_01dcde_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['patient', 'is_active'], name='treatments__patient_ef16bd_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['statut', 'is_active'], name='treatments__statut_78eb11_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['type_acte', 'is_active'], name='treatments__type_ac_3bcc82_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['dent', 'is_active'], name='treatments__dent_800840_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['date_debut'], name='treatments__date_de_bee48c_idx'),
        ),
        migrations.AddIndex(
            model_name='seancesoin',
            index=models.Index(fields=['traitement', 'is_active'], name='treatments__traitem_ca9125_idx'),
        ),
        migrations.AddIndex(
            model_name='seancesoin',
            index=models.Index(fields=['date'], name='treatments__date_e379fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seancesoin',
            unique_together={('traitement', 'numero_seance')},
        ),
    ]
